Partial Class FRMORDTSC
  Inherits FRM__CHIL

  <System.Diagnostics.DebuggerNonUserCode()> _
  Public Sub New()
    MyBase.New()
  End Sub

  'Form overrides dispose to clean up the component list.
  <System.Diagnostics.DebuggerNonUserCode()> _
  Protected Overloads Overrides Sub Dispose(ByVal disposing As Boolean)
    If disposing AndAlso components IsNot Nothing Then
      components.Dispose()
    End If
    MyBase.Dispose(disposing)
  End Sub

  'Required by the Windows Form Designer
  Private components As System.ComponentModel.IContainer
  Public WithEvents pnSpese As NTSInformatica.NTSPanel
  Public WithEvents cbEt_tippaga_8 As NTSInformatica.NTSComboBox
  Public WithEvents cbEt_tippaga_7 As NTSInformatica.NTSComboBox
  Public WithEvents cbEt_tippaga_6 As NTSInformatica.NTSComboBox
  Public WithEvents cbEt_tippaga_5 As NTSInformatica.NTSComboBox
  Public WithEvents cbEt_tippaga_4 As NTSInformatica.NTSComboBox
  Public WithEvents cbEt_tippaga_3 As NTSInformatica.NTSComboBox
  Public WithEvents cbEt_tippaga_2 As NTSInformatica.NTSComboBox
  Public WithEvents cbEt_tippaga_1 As NTSInformatica.NTSComboBox
  Public WithEvents edEt_datsca_8 As NTSInformatica.NTSTextBoxData
  Public WithEvents edEt_datsca_7 As NTSInformatica.NTSTextBoxData
  Public WithEvents edEt_datsca_6 As NTSInformatica.NTSTextBoxData
  Public WithEvents edEt_datsca_5 As NTSInformatica.NTSTextBoxData
  Public WithEvents edEt_datsca_4 As NTSInformatica.NTSTextBoxData
  Public WithEvents edEt_datsca_3 As NTSInformatica.NTSTextBoxData
  Public WithEvents edEt_datsca_2 As NTSInformatica.NTSTextBoxData
  Public WithEvents edEt_datsca_1 As NTSInformatica.NTSTextBoxData
  Public WithEvents edEt_impscav_8 As NTSInformatica.NTSTextBoxNum
  Public WithEvents edEt_impscav_7 As NTSInformatica.NTSTextBoxNum
  Public WithEvents edEt_impscav_6 As NTSInformatica.NTSTextBoxNum
  Public WithEvents edEt_impscav_5 As NTSInformatica.NTSTextBoxNum
  Public WithEvents edEt_impscav_4 As NTSInformatica.NTSTextBoxNum
  Public WithEvents edEt_impscav_3 As NTSInformatica.NTSTextBoxNum
  Public WithEvents edEt_impscav_2 As NTSInformatica.NTSTextBoxNum
  Public WithEvents edEt_impscav_1 As NTSInformatica.NTSTextBoxNum
  Public WithEvents lbImportoValuta As NTSInformatica.NTSLabel
  Public WithEvents lbImporto As NTSInformatica.NTSLabel
  Public WithEvents lbScadenza As NTSInformatica.NTSLabel
  Public WithEvents lbTipo As NTSInformatica.NTSLabel
  Public WithEvents lb8 As NTSInformatica.NTSLabel
  Public WithEvents edEt_impsca_8 As NTSInformatica.NTSTextBoxNum
  Public WithEvents lb7 As NTSInformatica.NTSLabel
  Public WithEvents edEt_impsca_7 As NTSInformatica.NTSTextBoxNum
  Public WithEvents lb6 As NTSInformatica.NTSLabel
  Public WithEvents edEt_impsca_6 As NTSInformatica.NTSTextBoxNum
  Public WithEvents lb5 As NTSInformatica.NTSLabel
  Public WithEvents lb4 As NTSInformatica.NTSLabel
  Public WithEvents lb3 As NTSInformatica.NTSLabel
  Public WithEvents lb2 As NTSInformatica.NTSLabel
  Public WithEvents edEt_impsca_5 As NTSInformatica.NTSTextBoxNum
  Public WithEvents edEt_impsca_4 As NTSInformatica.NTSTextBoxNum
  Public WithEvents edEt_impsca_3 As NTSInformatica.NTSTextBoxNum
  Public WithEvents edEt_impsca_2 As NTSInformatica.NTSTextBoxNum
  Public WithEvents lb1 As NTSInformatica.NTSLabel
  Public WithEvents edEt_impsca_1 As NTSInformatica.NTSTextBoxNum
  Public WithEvents cmdOk As NTSInformatica.NTSButton

End Class