Partial Class FRMVEPEVE_F
  Inherits FRM__CHIL

  <System.Diagnostics.DebuggerNonUserCode()> _
  Public Sub New()
    MyBase.New()

    ''This call is required by the Windows Form Designer.
    'InitializeComponent()

  End Sub

  'Form overrides dispose to clean up the component list.
  <System.Diagnostics.DebuggerNonUserCode()> _
  Protected Overrides Sub Dispose(ByVal disposing As Boolean)
    If disposing AndAlso components IsNot Nothing Then
      components.Dispose()
    End If
    MyBase.Dispose(disposing)
  End Sub
  Public WithEvents NtsTabPage5 As NTSInformatica.NTSTabPage
  Public WithEvents NtsPanel1 As NTSInformatica.NTSPanel
  Public WithEvents lbXx_tipobfrkq As NTSInformatica.NTSLabel
  Public WithEvents edTb_tipobfrkq As NTSInformatica.NTSTextBoxNum
  Public WithEvents lbTb_tipobfrkq As NTSInformatica.NTSLabel
  Public WithEvents lbXx_tipobfrkr As NTSInformatica.NTSLabel
  Public WithEvents edTb_tipobfrkr As NTSInformatica.NTSTextBoxNum
  Public WithEvents lbTb_tipobfrkr As NTSInformatica.NTSLabel
  Public WithEvents lbXx_tipobfrks As NTSInformatica.NTSLabel
  Public WithEvents edTb_tipobfrks As NTSInformatica.NTSTextBoxNum
  Public WithEvents lbTb_tipobfrks As NTSInformatica.NTSLabel
  Public WithEvents lbXx_tipobfrkn As NTSInformatica.NTSLabel
  Public WithEvents edTb_tipobfrkn As NTSInformatica.NTSTextBoxNum
  Public WithEvents lbTb_tipobfrkn As NTSInformatica.NTSLabel
  Public WithEvents lbXx_tipobfrkf As NTSInformatica.NTSLabel
  Public WithEvents lbXx_tipobfrki As NTSInformatica.NTSLabel
  Public WithEvents edTb_tipobfrki As NTSInformatica.NTSTextBoxNum
  Public WithEvents lbTb_tipobfrki As NTSInformatica.NTSLabel
  Public WithEvents edTb_tipobfrkf As NTSInformatica.NTSTextBoxNum
  Public WithEvents lbTb_tipobfrkf As NTSInformatica.NTSLabel
  Public WithEvents lbXx_tipobfrke As NTSInformatica.NTSLabel
  Public WithEvents edTb_tipobfrke As NTSInformatica.NTSTextBoxNum
  Public WithEvents lbTb_tipobfrke As NTSInformatica.NTSLabel
  Public WithEvents lbXx_tipobfrkc As NTSInformatica.NTSLabel
  Public WithEvents edTb_tipobfrkc As NTSInformatica.NTSTextBoxNum
  Public WithEvents lbTb_tipobfrkc As NTSInformatica.NTSLabel
  Public WithEvents lbXx_tipobfrkb As NTSInformatica.NTSLabel
  Public WithEvents edTb_tipobfrkb As NTSInformatica.NTSTextBoxNum
  Public WithEvents lbTb_tipobfrkb As NTSInformatica.NTSLabel
  Public WithEvents lbXx_tipobfrka As NTSInformatica.NTSLabel
  Public WithEvents edTb_tipobfrka As NTSInformatica.NTSTextBoxNum
  Public WithEvents lbTb_tipobfrka As NTSInformatica.NTSLabel
  Public WithEvents edXx_vlistin As NTSInformatica.NTSLabel

End Class